---

- name: Install python3 and librairies required by ansible.core.k8s
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python-is-python3
    - python3-pip
    - python3-kubernetes
    - python3-yaml
    - python3-jsonpatch
